
time_horizon:
  weather_history:
    end_date: "the date of the day that is 2 days before the current system JST date"
    start_date: "January 1st of the year that is 3 years before the end_date year"

  competitor_history:
    end_date: "the date of the day that is 2 days before the current system JST date"
    start_date: "January 1st of the year that is 5 years before the end_date year"

  home_building_history:
    end_date: "the date of the day that is 2 days before the current system JST date"
    start_date: "January 1st of the year that is 5 years before the end_date year"

  sales_history:
    end_date: "the date of the day that is 2 days before the current system JST date"
    start_date: "January 1st of the year that is 2 years before the end_date year"
    
  demand_forecast_training:
    end_date: "the date of the last day of the month that is 2 months before the month of current system JST date"
    start_date: "the date of first day of sales_history"

  demand_forcast_prediction:
    end_date: "the date of the day that is 7 days after the current system JST date"
    start_date: "the date of the day that is 1 day after the current system JST date"

  delivery_planning:
    end_date: "the date of the day that is 7 days after the current system JST date"
    start_date: "the date of the day that is 1 day after the current system JST date"


synthetics:
  random_seed: 629

  stores:
    weekday_sales_baseline: [80, 300]
    weekend_sales_baseline: [50, 350]    

  competitors:
    numbers:
      埼玉県: 300
      東京都: 600
      千葉県: 300
      神奈川県: 400

    weekday_sales_baseline: [30, 300]
    weekend_sales_baseline: [30, 300]
    business_duration: [90, 1825]

  home_buildings:
    numbers:
      埼玉県: 150
      東京都: 300
      千葉県: 150
      神奈川県: 200

    unit_range: [20, 300]

  events:
    numbers:
      埼玉県: 300
      東京都: 1000
      千葉県: 300
      神奈川県: 500

    people_range: [200, 1000]
