#!/usr/bin/env python3
"""Emit schema.sql (typed DuckDB views) + SCHEMA.md (data dictionary) from _spec.py.

Generated from the same registry the builders use, so the schema/dictionary can never
drift from the TSVs. Only tables whose TSV exists are included, so this works whether or
not the marts have been built yet.

  DuckDB usage (from DATA/s10_analysis/):
      duckdb analysis.duckdb -c ".read schema.sql"
      -- then: SELECT * FROM fact_forecast LIMIT 5;
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import find_repo_root, out_dir  # noqa: E402
from _spec import TABLES  # noqa: E402


def _sql_for(name: str, cols: list[tuple[str, str, str]]) -> str:
    coldefs = ",\n".join(f"    '{c}': '{t}'" for c, t, _n in cols)
    return (
        f"CREATE OR REPLACE VIEW {name} AS\n"
        f"SELECT * FROM read_csv('{name}.tsv', delim='\\t', header=true, nullstr='',\n"
        f"  columns={{\n{coldefs}\n  }});\n"
    )


def main() -> int:
    root = find_repo_root(Path(__file__).resolve())
    d = out_dir(root)
    present = [n for n in TABLES if (d / f"{n}.tsv").exists()]
    if not present:
        raise SystemExit("No s10_analysis TSVs found — run build_core.py first.")

    # schema.sql
    sql = ["-- Generated by build_schema.py — typed DuckDB views over the s10_analysis TSVs.",
           "-- Run from DATA/s10_analysis/:  duckdb analysis.duckdb -c \".read schema.sql\"", ""]
    for n in present:
        sql.append(_sql_for(n, TABLES[n]["columns"]))
    (d / "schema.sql").write_text("\n".join(sql), encoding="utf-8")

    # SCHEMA.md
    md = ["# `s10_analysis` — data dictionary",
          "",
          "Generated from `_spec.py`. Grain, columns, types, and source for each table.",
          "See [../../docs/analysis/s10_analysis_design.md](design) for rationale.", ""]
    for n in present:
        t = TABLES[n]
        md += [f"## `{n}`  ({t['layout']})",
               "",
               f"- **Grain:** {t['grain']}",
               f"- **Source:** {t['source']}",
               f"- {t['desc']}",
               "",
               "| column | type | note |",
               "|---|---|---|"]
        md += [f"| {c} | {ty} | {note} |" for c, ty, note in t["columns"]]
        md.append("")
    (d / "SCHEMA.md").write_text("\n".join(md), encoding="utf-8")

    print(f"  wrote schema.sql + SCHEMA.md ({len(present)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
